name: connect
description: A Secured Chat Application made in Flutter

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4

  # Google Sign In
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.30
  google_sign_in_ios: ^5.7.7

  # Explicitly upgrade problem packages
  shared_preferences: ^2.3.3
  shared_preferences_android: ^2.3.4
  flutter_plugin_android_lifecycle: ^2.0.22
  image_picker_android: ^0.8.12+16
  sqflite: ^2.4.1

  # State Management
  flutter_riverpod: ^2.5.1

  # UI Components
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^2.2.0

  # Utilities
  http: ^1.2.1
  gal: ^2.3.0

  # Connectivity Check (for Dino Game)
  connectivity_plus: ^6.0.5

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Animations & UI
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.1

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/logo-pic.png"
  min_sdk_android: 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env